
- name: Download repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

#- name: Ensure Python 3 and pip are installed
#  ansible.builtin.dnf:
#    name:
#      - python3
#      - python3-pip
#    state: present
#
#- name: Upgrade pip
#  ansible.builtin.pip:
#    name: pip
#    executable: python3 -m pip
#    state: latest
#
#- name: Install hvac Python library
#  ansible.builtin.pip:
#    name: hvac
#    executable: python3 -m pip

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Create GitHub Runner Container
  community.docker.docker_container:
    name: "{{ item }}"
    image: udaych123/github-runner
    pull: true
    state: started
    restart_policy: always
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/github-runner:ORG token=' + token + ' url=http://vault.yourtherapist.in:8200/') }}"
      TOKEN: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/github-runner:TOKEN token=' + token + ' url=http://vault.yourtherapist.in:8200/') }}"
  loop:
    - runner-1
    - runner-2
    - runner-3
