
- name: Download repo file
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/rhel/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  ansible.builtin.dnf:
    name: docker-ce
    state: installed

- name: Install Python 3.12 and pip using dnf
  ansible.builtin.dnf:
    name:
      - python3.12
      - python3.12-pip
    state: present

- name: Ensure pip is available for Python 3.12
  ansible.builtin.command: python3.12 -m ensurepip --upgrade
  args:
    creates: /usr/local/lib/python3.12/site-packages/pip

- name: Upgrade pip for Python 3.12
  ansible.builtin.command: python3.12 -m pip install --upgrade pip

- name: Install Python packages (hvac and ansible) for Python 3.12
  ansible.builtin.dnf: python3.12 -m pip install hvac ansible
  state: present

- name: Start Docker
  ansible.builtin.systemd_service:
    name: docker
    state: started
    enabled: yes

- name: Create GitHub Runner Container
  community.docker.docker_container:
    name: "{{ item }}"
    image: udaych123/github-runner
    pull: true
    state: started
    restart_policy: always
    env:
      ORG: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/github-runner:ORG token=' + token + ' url=http://vault.yourtherapist.in:8200/') }}"
      TOKEN: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=kv/data/github-runner:TOKEN token=' + token + ' url=http://vault.yourtherapist.in:8200/') }}"
  loop:
    - runner-1
    - runner-2
    - runner-3
